version: '3'
services:
  nginxgwsvc:
    image: nginxgw
    container_name: nginxgw
    networks:
      - net1
    ports:
      - 80:80
      - 443:443
    environment:
      TZ : America/New_York
    volumes:
      - ./data/sites:/var/www/sites
      - ./data/sites-enabled:/etc/nginx/sites-enabled
      - ./data/letsencrypt:/etc/letsencrypt
networks:
  net1:
    driver: bridge